"""initial schema

Revision ID: 994f86e80a0e
Revises: 
Create Date: 2026-07-26 12:26:23.165369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '994f86e80a0e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_name', sa.String(length=80), nullable=False),
    sa.Column('public_directory_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('list_name', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=4), nullable=False),
    sa.Column('decimal_separator', sa.String(length=10), nullable=False),
    sa.Column('theme_color', sa.String(length=7), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('show_image_placeholder', sa.Boolean(), nullable=False),
    sa.Column('share_token', sa.String(length=64), nullable=False),
    sa.Column('show_in_directory', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_token'),
    sa.UniqueConstraint('username')
    )
    op.create_table('gift',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=True),
    sa.Column('brand', sa.String(length=80), nullable=True),
    sa.Column('options', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('claimed_by', sa.String(length=100), nullable=True),
    sa.Column('claim_token', sa.String(length=64), nullable=True),
    sa.Column('purchased', sa.Boolean(), nullable=False),
    sa.Column('received', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gift')
    op.drop_table('user')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
